language: ruby
dist: bionic
cache: bundler

before_install:
- sudo apt-get install -y libsystemd-dev
- echo 'aaaaaaaa' > passphrase_file
- echo $DEBSIGN | base64 -d | gpg --import --batch

script:
- bundle install
- make -j $(grep -c ^processor /proc/cpuinfo)

after_success:
- gpg --list-secret-keys
- bundle exec deb-s3 upload --s3-region=eu-west-1 --sign=6A2561804E290210909454E69640EFFBAA3B94A5 --gpg-options="\-\-pinentry\-mode=loopback \-\-passphrase\-file passphrase_file \-\-batch" --suite stable --origin "Andrew Rowson" --bucket apt-growse-com promtail_*.deb
