language: go
dist: bionic

before_install:
- sudo apt-get install -y libsystemd-dev
- echo 'aaaaaaaa' > passphrase_file
- echo $DEBSIGN | base64 -d | gpg --import --batch
- bundle install

script:
- make -j $(grep -c ^processor /proc/cpuinfo)

deploy:
  skip_cleanup: true
  provider: script
  script: bundle install && bundle exec deb-s3 upload --s3-region=eu-west-1 --sign=6A2561804E290210909454E69640EFFBAA3B94A5 --gpg-options="\-\-pinentry\-mode=loopback \-\-passphrase\-file passphrase_file \-\-batch" --suite stable --origin "Andrew Rowson" --bucket apt-growse-com promtail_*.deb
