name: Build, package and deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Install libsystemd-dev & cross-compiler
        run: sudo apt update && sudo apt install -y libsystemd-dev git gccgo-aarch64-linux-gnu gccgo-arm-linux-gnueabi
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Build
        run: make build
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: gopath/src/github.com/grafana/loki/dist
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: changelog
          path: gopath/src/github.com/grafana/loki/CHANGELOG.md
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    if: github.event_name != 'pull_request'
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Download site artifact
        uses: actions/download-artifact@v1
        with:
          name: dist
          path: gopath/src/github.com/grafana/loki/dist
      - name: Download changelog artifact
        uses: actions/download-artifact@v1
        with:
          name: changelog
          path: gopath/src/github.com/grafana/loki
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Install gems
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Make deb package
        run: |
          touch gopath/src/github.com/grafana/loki/dist/*
          make package
        env:
          BUILD_NUMBER: ${{ github.run_number }}
      - name: Upload to S3 Apt repo
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DEBSIGN: ${{ secrets.DEBSIGN }}
        run: |
          echo 'aaaaaaaa' > passphrase_file
          echo $DEBSIGN | base64 -d | gpg --import --batch
          bundle exec deb-s3 upload --s3-region=eu-north-1 --sign=6A2561804E290210909454E69640EFFBAA3B94A5 --gpg-options="\-\-pinentry\-mode=loopback \-\-passphrase\-file passphrase_file \-\-batch" --suite stable --origin "Andrew Rowson" --bucket apt.growse.com *.deb
